name: Create and publish a Docker image

env:
  REGISTRY: ghcr.io
  DOCKERIMAGETAG: latest

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dockerimagetag:
        default: "latest"
        description: "Docker image tag"
        required: true
        type: string

jobs:
  print-input:
    if: ${{ inputs.dockerimagetag }}
    runs-on: ubuntu-latest
    steps:
      - name: Print input value to stdout
        run: echo Input value _${{ inputs.dockerimagetag }}_
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print env value to stdout
        run: echo Input value _${{ env.DOCKERIMAGETAG }}_

