on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  test-global-for-input:
    runs-on: ubuntu-latest
    steps:
       - run: echo "Passed input: ${{ inputs.env_name }}
