name: Create and publish a Docker image

env:
  DOCKERIMAGE: docker-ficy
  # TODO: keep investigating how to use input and its default value
  DOCKERIMAGETAG: latest
  REGISTRY: ghcr.io
  USER: contrabanda-fm

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dockerimagetag:
        # TODO: keep investigating how to use input and its default value
        default: "latest"
        description: "Docker image tag"
        required: true
        type: string

jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image using default docker image tag
        uses: docker/build-push-action@v4
        with:
          build-args: |
            IMAGE=debian
            VERSION=latest
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.DOCKERIMAGE }}:${{ env.DOCKERIMAGETAG }}
      # Below step only executed if action triggered manually
      - name: Build and push Docker image using input docker image tag
        if: ${{ inputs.dockerimagetag }}
        uses: docker/build-push-action@v4
        with:
          build-args: |
            IMAGE=debian
            VERSION=latest
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.DOCKERIMAGE }}:${{ inputs.dockerimagetag }}

