name: Example Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Print Repo Name
      run: echo $GITHUB_REPOSITORY
