name: Create and publish a Docker image

env:
  REGISTRY: ghcr.io

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        default: 'latest'
        description: 'Docker image tag'
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            IMAGE=debian
            VERSION=latest
          context: .
          push: true
          tags: |
            ghcr.io/my-username/my-image:${{ github.sha }}
            ghcr.io/my-username/my-image:${{ github.event.inputs.tag }}
