name: Create and publish a Docker image

env:
  REGISTRY: ghcr.io

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Print input value to stdout
        run: echo Input value _${{ inputs.input1 }}_
          input1: value1
